swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/bankAccount/{id}:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User bank account API
      description: API for fetching a user bank account
      parameters:
      - name: id
        in: path
        description: User bank account ID
        required: true
        type: string
      responses:
        '200':
          description: User bank account retrieved successully
          schema:
              type: object
              properties:
                status:
                  type: integer
                message:
                  type: string
                body:
                  type: object
                  properties:
                    id:
                      type: string
                    date:
                      type: string
                    description: 
                      type: string
                    amount: 
                      type: string
                    balance: 
                      type: string
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error   
  /user/bankAccount/{id}/transaction/{id}:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User bank account transaction API
      description: API for fetching transaction from user bank account
      parameters:
      - name: id
        in: path
        description: User bank account transaction id
        required: true
        type: string
      responses:
        '200':
          description: User bank account transaction retrieved successully
          schema:
              type: object
              properties:
                status:
                  type: integer
                message:
                  type: string
                body:
                  type: object
                  properties:
                    id:
                      type: string
                    transaction type:
                      type: string
                    category: 
                      type: string
                    note: 
                      type: string
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error  
  /user/bankAccount/{id}/transaction/{id}/note/{id}:
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update transaction note
      description: API to updating transaction note
      parameters:
        - name: id
          in: path
          description: User bank account transaction id
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction note
          required: true
          schema:
              type: object
              properties:
                  note:
                    type: string
                    required: [note]
      responses:
        '200':
          description: User bank account transaction note retrieved successully
          schema:
              type: object
              properties:
                status:
                  type: integer
                message:
                  type: string
                body:
                  type: object
                  properties:
                    id:
                      type: string
                    transaction type:
                      type: string
                    category: 
                      type: string
                    note: 
                      type: string
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error        
  /user/bankAccount/{id}/transaction/{id}/category/{id}:
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update transaction category
      description: API to updating transaction category
      parameters:
        - name: id
          in: path
          description: User bank account transaction id
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction category
          required: true
          schema:
              type: object
              properties:
                  category:
                    type: string
                    required: [category]
      responses:
        '200':
          description: User bank account transaction category retrieved successully
          schema:
              type: object
              properties:
                status:
                  type: integer
                message:
                  type: string
                body:
                  type: object
                  properties:
                    id:
                      type: string
                    transaction type:
                      type: string
                    category: 
                      type: string
                    note: 
                      type: string
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error               
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
